services:
  artwork_uploader:
    image: ghcr.io/mscodemonkey/artwork-uploader:latest
    container_name: artwork-uploader
    ports:
      - "4567:4567"
    volumes:
      - ./bulk_imports:/artwork-uploader/bulk_imports:rw
      - ./config:/artwork-uploader/config:rw
      - ./logs:/artwork-uploader/logs:rw

      # OPTIONAL: Media paths (required for Plex local media assets mode)
      # Artwork Uploader must have access to all media folders assigned to Plex libraries
      # where local assets would potentially need to be saved. The host paths must be the 
      # actual paths at the host level, and the container path names are arbitrary, but they
      # will be used if path mappings need to be defined.
      #
      # If Plex is also running as a container, use the same container paths here to
      # avoid having to define path mappings
      - <HOST_PATH_TO_MEDIA_FOLDER_1>:/media/movies1:rw
      - <HOST_PATH_TO_MEDIA_FOLDER_2>:/media/movies2:rw
      - <HOST_PATH_TO_MEDIA_FOLDER_3>:/media/tv1:rw
      - <HOST_PATH_TO_MEDIA_FOLDER_4>:/media/tv2:rw
      # Add as many bind mounts as root folders for media libraries you have in Plex

      # OPTIONAL: Kometa settings (required for Kometa asset directory mode)
      - <HOST_PATH_TO_KOMETA_ASSET_DIRECTORY>:/assets:rw # Optional, only if you save assets to your Kometa asset directory
      - <HOST_TEMP_PATH>:/temp:rw # Optional, only for testing with a temp dir
    environment:
      - TZ=Europe/London
      - RUNNING_IN_DOCKER=1
    restart: unless-stopped
